/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2024-06-27 11:11:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  font-family: Roboto;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  \r\n");
      out.write("  background: linear-gradient(120deg, #007bff, #d0314c);\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("  width: 29vw;\r\n");
      out.write("  background: white;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center h1{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 0 0 20px 0;\r\n");
      out.write("  border-bottom: 1px solid silver;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center form{\r\n");
      out.write("  padding: 0 40px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form .txt_field{\r\n");
      out.write("  position: relative;\r\n");
      out.write("  border-bottom: 2px solid #adadad;\r\n");
      out.write("  margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt_field input{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 0 5px;\r\n");
      out.write("  height: 40px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  background: none;\r\n");
      out.write("  outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt_field label{\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 5px;\r\n");
      out.write("  color: #adadad;\r\n");
      out.write("  transform: translateY(-50%);\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  pointer-events: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt_field span::before{\r\n");
      out.write("  content: '';\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 40px;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  width: 0px;\r\n");
      out.write("  height: 2px;\r\n");
      out.write("  background: #2691d9;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt_field input:focus ~ label,\r\n");
      out.write(".txt_field input:valid ~ label{\r\n");
      out.write("  top: -5px;\r\n");
      out.write("  color: #2691d9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt_field input:focus ~ span::before,\r\n");
      out.write(".txt_field input:Valid ~ span::before{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass{\r\n");
      out.write("  margin: -5px 0 20px 5px;\r\n");
      out.write("  color: #a6a6a6;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass:hover{\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"Submit\"]{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  border: 1px solid;\r\n");
      out.write("  border-radius: 25px;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  font-weight: 700;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"Submit\"]:hover{\r\n");
      out.write("  background: #2691d9;\r\n");
      out.write("  color: #e9f4fb;\r\n");
      out.write("  transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup_link{\r\n");
      out.write("  margin: 30px 0;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup_link a{\r\n");
      out.write("  color: #2691d9;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup_link a:hover{\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".HomeAbout{\r\n");
      out.write("  width: 100vw;\r\n");
      out.write("  height: 25vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("      <div class=\"center\">\r\n");
      out.write("          <h1>Login</h1>\r\n");
      out.write("          \r\n");
      out.write("          <form action=\"find\" method=\"POST\">\r\n");
      out.write("              <div class=\"txt_field\">\r\n");
      out.write("                  <input type=\"text\" name=\"email\" required>\r\n");
      out.write("                  <span></span>\r\n");
      out.write("                  <label>Username</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"txt_field\">\r\n");
      out.write("                  <input type=\"password\" name=\"passwords\" required>\r\n");
      out.write("                  <span></span>\r\n");
      out.write("                  <label>Password</label>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"pass\">Forget Password?</div>\r\n");
      out.write("              <input name=\"submit\" type=\"Submit\" value=\"Login\">\r\n");
      out.write("              <div class=\"signup_link\">\r\n");
      out.write("              <h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("                  Not a Member ? <a href=\"Register.jsp\">Signup</a>\r\n");
      out.write("              </div>\r\n");
      out.write("          </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
